export const LIMA_DISTRICTS = [
  { id: "ancon", name: "Ancón" },
  { id: "ate", name: "Ate" },
  { id: "barranco", name: "Barranco" },
  { id: "breña", name: "Breña" },
  { id: "carabayllo", name: "Carabayllo" },
  { id: "chaclacayo", name: "Chaclacayo" },
  { id: "chorrillos", name: "Chorrillos" },
  { id: "cieneguilla", name: "Cieneguilla" },
  { id: "comas", name: "Comas" },
  { id: "el_agustino", name: "El Agustino" },
  { id: "independencia", name: "Independencia" },
  { id: "jesus_maria", name: "Jesús María" },
  { id: "la_molina", name: "La Molina" },
  { id: "la_victoria", name: "La Victoria" },
  { id: "lince", name: "Lince" },
  { id: "los_olivos", name: "Los Olivos" },
  { id: "lurigancho", name: "Lurigancho" },
  { id: "lurin", name: "Lurín" },
  { id: "magdalena", name: "Magdalena del Mar" },
  { id: "miraflores", name: "Miraflores" },
  { id: "pachacamac", name: "Pachacamac" },
  { id: "pucusana", name: "Pucusana" },
  { id: "pueblo_libre", name: "Pueblo Libre" },
  { id: "puente_piedra", name: "Puente Piedra" },
  { id: "punta_hermosa", name: "Punta Hermosa" },
  { id: "punta_negra", name: "Punta Negra" },
  { id: "rimac", name: "Rímac" },
  { id: "san_bartolo", name: "San Bartolo" },
  { id: "san_borja", name: "San Borja" },
  { id: "san_isidro", name: "San Isidro" },
  { id: "san_juan_lurigancho", name: "San Juan de Lurigancho" },
  { id: "san_juan_miraflores", name: "San Juan de Miraflores" },
  { id: "san_luis", name: "San Luis" },
  { id: "san_martin_porres", name: "San Martín de Porres" },
  { id: "san_miguel", name: "San Miguel" },
  { id: "santa_anita", name: "Santa Anita" },
  { id: "santa_maria", name: "Santa María del Mar" },
  { id: "santa_rosa", name: "Santa Rosa" },
  { id: "santiago_surco", name: "Santiago de Surco" },
  { id: "surquillo", name: "Surquillo" },
  { id: "villa_el_salvador", name: "Villa El Salvador" },
  { id: "villa_maria_triunfo", name: "Villa María del Triunfo" },
].sort((a, b) => a.name.localeCompare(b.name));
